#!/usr/bin/env bash
# evolve_pr.sh — 自进化 PR 流程（B 改代码 → 守门 → 开 PR → merge）
#
# 流程：
#   1. A 启动 container + 编译 ion/ion-worker
#   2. A 驱动 B 改代码（container exec，用 stdin 喂 prompt）
#   3. A 守门（U+FFFD + cargo build + cargo test）
#   4. 通过 → 在 host 上创建 feature 分支 + push + 开 PR
#   5. PR 自动 merge（cargo test 通过即 auto-merge）
#   6. 导出 HTML 报告
#
# Usage: bash scripts/evolve_pr.sh "任务描述"
set -uo pipefail

PROJECT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
CONTAINER_BIN="${CONTAINER_BIN:-/usr/local/bin/container}"
MODEL="${MODEL:-glm-5.2}"
PROVIDER="${PROVIDER:-zai}"
TASK_DESC="${1:-Add a utility method with test to src/global_memory.rs. ALL comments ENGLISH.}"

source /tmp/.evolver-state 2>/dev/null
if [ -z "$CONTAINER_NAME" ] || [ -z "$WT_DIR" ]; then
    echo "ERROR: Run scripts/evolve.sh first"
    exit 1
fi

cd "$PROJECT_DIR"

echo ""
echo "=========================================="
echo "  Self-Evolution via PR"
echo "=========================================="
echo "  Task:     $TASK_DESC"
echo "  Model:    $MODEL"
echo "  Provider: $PROVIDER"
echo "=========================================="
echo ""

# ── Step 1: A 驱动 B 改代码 ────────────────────────────────────────
echo "Step 1: Driving B to write code..."
B_RESULT=$(echo "Task: $TASK_DESC

CRITICAL RULES:
1. Use edit tool, not bash sed
2. ALL comments in ENGLISH ONLY
3. Only ADD new code, do NOT modify existing lines
4. Do NOT modify Cargo.toml
5. After editing: cargo check
6. git add -A && git commit -m 'feat: self-evolution change'
7. grep -c \$'\xef\xbf\xbd' src/*.rs (must be 0)" \
    | "$CONTAINER_BIN" exec -i "$CONTAINER_NAME" sh -c \
    "cd /workspace && ./target/release/ion --agent developer --provider $PROVIDER --model $MODEL" 2>&1 | tail -10)

echo "$B_RESULT"
echo ""

# ── Step 2: 看 B 改了什么 ─────────────────────────────────────────
echo "Step 2: Checking B's changes..."
CHANGED_FILES=$("$CONTAINER_BIN" exec "$CONTAINER_NAME" sh -c 'cd /workspace && git diff --name-only HEAD~1 HEAD 2>/dev/null || git diff --name-only 2>/dev/null' 2>/dev/null)
if [ -z "$CHANGED_FILES" ]; then
    echo "❌ No changes detected. B may have failed."
    exit 1
fi
echo "Changed files: $CHANGED_FILES"
echo ""

# ── Step 3: 守门 ──────────────────────────────────────────────────
echo "Step 3: Gate checks..."

# U+FFFD 检查
for f in $CHANGED_FILES; do
    UFFFD=$("$CONTAINER_BIN" exec "$CONTAINER_NAME" sh -c "grep -c \$'\\xef\\xbf\\xbd' /workspace/$f 2>/dev/null || true" 2>/dev/null | head -1 | tr -d '[:space:]')
    if [ "$UFFFD" != "0" ]; then
        echo "❌ U+FFFD in $f ($UFFFD). Aborting."
        exit 1
    fi
done
echo "✅ U+FFFD check passed"

# 同步到 host
for f in $CHANGED_FILES; do
    "$CONTAINER_BIN" exec "$CONTAINER_NAME" sh -c "cat /workspace/$f" > "$PROJECT_DIR/$f" 2>/dev/null
done

# cargo build
echo "Running cargo build..."
BUILD_OUT=$(cargo build --bin ion 2>&1)
if ! echo "$BUILD_OUT" | grep -q "Finished"; then
    echo "❌ cargo build failed"
    echo "$BUILD_OUT" | grep "error" | head -3
    for f in $CHANGED_FILES; do git checkout -- "$f"; done
    exit 1
fi
echo "✅ cargo build passed"

# cargo test
echo "Running cargo test..."
TEST_OUT=$(cargo test --lib 2>&1)
if ! echo "$TEST_OUT" | grep -q "test result: ok"; then
    echo "❌ cargo test failed"
    echo "$TEST_OUT" | grep "FAILED" | head -3
    for f in $CHANGED_FILES; do git checkout -- "$f"; done
    exit 1
fi
PASSED=$(echo "$TEST_OUT" | grep -oE "[0-9]+ passed" | head -1)
echo "✅ cargo test passed: $PASSED"
echo ""

# ── Step 4: 创建 feature 分支 + push + 开 PR ─────────────────────
echo "Step 4: Creating PR..."

BRANCH="evolve/$(date +%Y%m%d-%H%M%S)"

git checkout -b "$BRANCH" 2>&1 | head -1
git add -A
COMMIT_MSG="feat(evolve): $TASK_DESC (via PR flow, $PASSED)"
git commit -m "$COMMIT_MSG" 2>&1 | head -1

echo "Pushing branch..."
git push origin "$BRANCH" 2>&1 | tail -3

echo ""
echo "Creating PR..."
PR_URL=$(gh pr create \
    --title "$COMMIT_MSG" \
    --body "## Self-Evolution Change

**Task**: $TASK_DESC

**Changed files**:
\`\`\`
$CHANGED_FILES
\`\`\`

**Verification**:
- ✅ U+FFFD check: 0
- ✅ cargo build: passed
- ✅ cargo test: $PASSED

**Model**: $MODEL ($PROVIDER)
**Generated by**: evolve_pr.sh (A→B self-evolution)
" \
    --base master \
    --head "$BRANCH" 2>&1)

echo "PR: $PR_URL"
echo ""

# ── Step 5: Auto-merge（测试通过即 merge）─────────────────────────
echo "Step 5: Auto-merging (tests passed)..."
gh pr merge "$BRANCH" --merge --delete-branch 2>&1 | tail -3

git checkout master 2>&1 | head -1
git pull origin master 2>&1 | tail -2

echo ""
echo "=========================================="
echo "  PR Flow Complete"
echo "=========================================="
echo "  Branch:  $BRANCH (merged + deleted)"
echo "  PR:      $PR_URL"
echo "  Tests:   $PASSED"
echo "=========================================="